theme: jekyll-theme-minimal
title: Danila Rassokhin
author: Danila Rassokhin
description: My personal web page
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
