theme: jekyll-theme-minimal
title: Danila Rassokhin
author: Danila Rassokhin
description: My personal web page
logo: https://avatars.githubusercontent.com/u/111862432?s=200&v=4
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
